services:
  - type: web
    name: nimiq-arena
    runtime: node
    plan: free
    buildCommand: pnpm install --no-frozen-lockfile && pnpm run build
    startCommand: pnpm start
    healthCheckPath: /api/health
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: NIMIQ_NETWORK_ID
        value: "5"
      - key: NIMIQ_RPC_URL
        value: "https://rpc.testnet.nimiqwatch.com"
      - key: TRUST_PROXY
        value: "1"
      - key: DATABASE_URL
        sync: false
      - key: NIMIQ_PAYMENT_RECIPIENT
        value: "NQ51 85HV UT5T 22TU SKH3 50ED NSKL FKMK 0CJX"
      - key: NIMIQ_SETTLEMENT_ADDRESS
        value: "NQ51 85HV UT5T 22TU SKH3 50ED NSKL FKMK 0CJX"
      - key: ENABLE_AUTOMATED_PAYOUTS
        value: "true"
      - key: NIMIQ_PAYOUT_PRIVATE_KEY
        sync: false
      - key: NIMIQ_BUILDER_ADDRESS
        value: "NQ51 85HV UT5T 22TU SKH3 50ED NSKL FKMK 0CJX"
      - key: NIMIQ_CHARITY_ADDRESS
        value: "NQ44 KUSA 4K5M 5LMJ JKET 1GLB 0T8R 9J63 LMJ3"
      - key: NIMIQ_ECOSYSTEM_ADDRESS
        value: "NQ26 DH1P 5F4E H3PE 6STN 54MH 8296 G0UK 29AE"
      - key: DISABLE_PAYOUT_LIMITS
        value: "true"
      - key: DISCORD_WEBHOOK_URL
        sync: false
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: TELEGRAM_CHAT_ID
        sync: false
